[config]
default_to_workspace = false
skip_core_tasks = true

[env]
RUST_BACKTRACE = "full"
ALCHEMY_MUMBAI_API_KEY = "https://polygon-mumbai.g.alchemy.com/v2/VDEtXZglGFw5AoR48KaAj-ngFWYUehMY"
OWNER_PRIVATE_KEY = "6aea615c3d873b52514bed23b33011ffea8d1e99a242fa3d459b24dc21c93f3d"
OWNER_ADDRESS = "0x6c29233170269A10283c15ee2dFbB2d70Ba4E5B7"
CONTRACT_ADDRESS = "0x307B04Fd818eD3620847cE88fAfa73b80e090E79"

[tasks.build]
run_task = { name = [
    "build-frontend",
    "build-backend",
], fork = true, parallel = false }

[tasks.build-backend]
cwd = "./backend/"
command = "cargo"
args = ["build", "--release"]

[tasks.build-frontend]
dependencies = ["build-wasm-verifier", "install-frontend"]
cwd = "./frontend/"
command = "yarn"
args = ["build"]

[tasks.build-wasm-verifier]
cwd = "./wasm-verifier/"
command = "wasm-pack"
args = ["build", "--release", "--target", "web", "--out-dir", "../frontend/wasm-verifier"]

[tasks.install-frontend]
cwd = "./frontend/"
command = "yarn"

[tasks.run]
run_task = { name = [
    "run-backend",
    "run-frontend",
], fork = true, parallel = true }

[tasks.run-backend]
cwd = "./backend/"
command = "cargo"
args = ["run", "--release"]

[tasks.run-frontend]
dependencies = ["build-wasm-verifier", "install-frontend"]
cwd = "./frontend/"
command = "yarn"
args = ["dev"]
