[config]
default_to_workspace = false
skip_core_tasks = true

[env]
RUST_BACKTRACE = "full"
TEST_VAT = "SOME TEST VALUE"
ALCHEMY_MUMBAI_API_KEY = "https://polygon-mumbai.g.alchemy.com/v2/VDEtXZglGFw5AoR48KaAj-ngFWYUehMY"
OWNER_PRIVATE_KEY = "6aea615c3d873b52514bed23b33011ffea8d1e99a242fa3d459b24dc21c93f3d"
OWNER_ADDRESS = "0x6c29233170269A10283c15ee2dFbB2d70Ba4E5B7"

[tasks.build]
run_task = { name = [
    "build-backend",
    "build-wasm-verifier",
    "build-frontend",
], fork = true, parallel = false }

[tasks.build-release]
run_task = { name = [
    "build-release-backend",
    "build-release-wasm-verifier",
    "build-release-frontend",
], fork = true, parallel = false }

[tasks.run]
dependencies = ["build"]
run_task = { name = [
    "run-backend",
    "run-frontend",
], fork = true, parallel = true }

[tasks.run-release]
dependencies = ["build-release"]
run_task = { name = [
  "run-release-backend",
  "run-release-frontend",
], fork = true, parallel = true }

[tasks.build-wasm-verifier]
cwd = "./wasm-verifier/"
command = "wasm-pack"
args = ["build", "--target", "web", "--out-dir", "../frontend/wasm-verifier"]

[tasks.build-release-wasm-verifier]
cwd = "./wasm-verifier/"
command = "wasm-pack"
args = ["build", "--release", "--target", "web", "--out-dir", "../frontend/wasm-verifier"]

[tasks.build-backend]
cwd = "./backend/"
command = "cargo"
args = ["build"] # TODO: update backend tasks

[tasks.build-release-backend]
cwd = "./backend/"
command = "cargo"
args = ["build", "--release"] # TODO: update backend tasks

[tasks.run-backend]
cwd = "./backend/"
command = "cargo"
args = ["run"] # TODO: update backend tasks

[tasks.run-release-backend]
cwd = "./backend/"
command = "cargo"
args = ["run", "--release"] # TODO: update backend tasks

[tasks.install-frontend]
cwd = "./frontend/"
command = "yarn"

[tasks.build-frontend]
dependencies = ["install-frontend", "build-wasm-verifier"]
cwd = "./frontend/"
command = "yarn"
args = ["build"]

[tasks.build-release-frontend]
dependencies = ["install-frontend", "build-release-wasm-verifier"]
cwd = "./frontend/"
command = "yarn"
args = ["build"]

[tasks.run-frontend]
dependencies = ["build-frontend"]
cwd = "./frontend/"
command = "yarn"
args = ["dev"]

[tasks.run-release-frontend]
dependencies = ["build-release-frontend"]
cwd = "./frontend/"
command = "yarn"
args = ["preview"]
