[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
hex = "0.4"
methods = { path = "../methods" }
rand = "0.8"
risc0-zkvm = "0.14"
serde = { version = "1.0", features = ["derive"] }
wordle-core = { path = "../core" }
